default:
  tags: [docker]

stages:
  - ğŸ‰ Prepare
  - âœ”ï¸ Validate
  - ğŸ“¦ Build
  - ğŸš€ Deploy
  - ğŸš¨ Destroy

include:
  - local: ".gitlab/ci/Common.gitlab-ci.yml"
  - local: ".gitlab/ci/Terraform.gitlab-ci.yml"
